baseURL = 'https://satriacode.org/'
languageCode = 'en-us'
title = 'Komunitas IT Purwokerto'
theme = 'anatole-1.13.0'
summarylength = 70
[params]
title = 'SatriaCode'
author = "SatriaCode"
description = "Wadah Komunitas IT Purwokerto untuk <strong>Berkreasi</strong>, <strong>Terkoneksi</strong> dan <strong>Berkolaborasi</strong>"
profilePicture = "images/pp.png"
readMore = true
[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:root.satriacode@gmail.com"
[[params.socialIcons]] 
icon = "fab fa-instagram" 
title = "Instagram" 
url = "https://www.instagram.com/satriacode/"
[markup.goldmark.renderer]
unsafe= true